FROM someimage:latest as builder
RUN echo " Installing LIBS "
WORKDIR /code
COPY ./test ./test
RUN echo " BUILDING APP "

FROM alpine:latest as unittest
WORKDIR /unitTest
COPY --from=builder /code/test ./test
RUN echo "RUNNING THE UNITTEST" > /test

FROM alpine:latest as Securitycheck
WORKDIR	/sec
COPY --from=builder /code/* ./
COPY --from=unittest /unittest/test ./test
RUN echo "RUNNING THE SECURITY" >> /test


FROM alpine:latest as emailalert
WORKDIR	/reports
COPY --from=Securitycheck /sec/test ./test
RUN echo "SENDING REPORTS" >> /test


FROM alpine:latest as webapp
WORKDIR /code
COPY --from=builder /sec/*.py ./
CMD echo "process completed"


